version: '3.8'
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app:delegated
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - MONGO_URI=mongodb://192.168.0.247:27017/chore_tracker
    restart: always